rstapp/urls.py
from django.conf.urls import url

from . import views

app_name = 'rstapp'

urlpatterns = [
    url(r'^$', views.HomeView.as_view(), name='home'),
    url(r'create_rst$', views.create_rst, name='create_rst'),
    url(r'presentation_list$', views.present_all_presentation, name='presentation_list'),
    url(r'upload_pic', views.upload_pic, name='upload_pic'),
]

rsthtml/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'', include('rstapp.urls')),
    url(r'^admin/', admin.site.urls),
]

rstapp/models.py
from django.db import models

# Create your models here.


class Presentation(models.Model):
    name = models.CharField(max_length=200)
    content = models.CharField(max_length=99999)
    style = models.CharField(max_length=100)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.name

rstapp/views.py
from django.shortcuts import render
from django.views import generic
from django.http import HttpRequest , HttpResponse , HttpResponseRedirect
from django.template import loader
from django.core.urlresolvers import reverse
from django.core.files.storage import default_storage
from .models import Presentation
from django.utils import timezone
from django.http import JsonResponse
from django.core import serializers
from django.forms.models import model_to_dict
import json

import os


class HomeView(generic.ListView):
    template_name = 'rstapp/home.html'

    def get_queryset(self):

        return None


def create_rst(request):

    # Get file form HTML
    file_name = request.POST["presentation_name"]

    if not Presentation.objects.filter(name=file_name):
        new_file = Presentation(name=file_name, pub_date=timezone.now())
        new_file.save()

    rst_dir_path = 'rstapp/static/rstapp/rst_files'
    presentation_html_dir_path = "rstapp/static/rstapp/rst_to_html_files"
    presentation_style = request.POST["style_presentation"]

    # Write file
    content = request.POST["content"]
    rst_file = open('{}/{}.rst'.format(rst_dir_path, file_name), 'w')
    rst_file.write(content)
    rst_file.close()

    # Create presentation
    os.system('rst2html5 {} {}/{}.rst > {}/{}.html'.format(presentation_style, rst_dir_path, file_name,
                                                           presentation_html_dir_path, file_name))
    # Open presentation
    html_file = open("{}/{}.html".format(presentation_html_dir_path, file_name), "r")
    html_text = html_file.read()

    # Picture Upload

    if request.FILES:
        save_pic = request.FILES['upload']
        save_pic_dir = 'rstapp/static/rstapp/images/'
        save_pic_path = default_storage.save(save_pic_dir, save_pic)
        os.rename(save_pic_path, "{}{}".format(save_pic_dir, request.FILES['upload'].name))

    return HttpResponse(html_text)


def present_all_presentation(request):
    latest_presentation_list = Presentation.objects.order_by('pub_date')

    list_name = []
    for name in latest_presentation_list:
        list_name.append(name.name)

    list_name_json = json.dumps(list_name)

    # dict_obj = model_to_dict(latest_presentation_list)
    # latest_presentation_list_serialized = serializers.serialize('json', latest_presentation_list)
    # serialized = json.dumps(dict_obj)
    # presentation_list = JsonResponse(latest_presentation_list_serialized, safe=False)

    # return render(request, 'rstapp/presentation_list.html', presentation_list)
    return render(request, 'rstapp/presentation_list.html', {'latest_presentation_list': list_name_json})
    # return HttpResponse(json.dumps(latest_presentation_list_serialized))
    # return JsonResponse(latest_presentation_list_serialized, safe=False)
    # return HttpResponse(serialized)


def upload_pic(request):
    data = {}
    return JsonResponse(data)


def upload_file(request):
    if request.FILES:
        rst_dir_path = 'rstapp/static/rstapp/rst_files'
        presentation_html_dir_path = "rstapp/static/rstapp/rst_to_html_files"

        '''csv_file = request.FILES['csvfile']
        file_path = default_storage.save(dir_path, csv_file)
        os.rename(file_path, "{}word_bank.csv".format(dir_path))'''

rstapp/templates/rstapp/edit_rst.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

rstapp/templates/rstapp/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home</title>
</head>

<script src="http://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.min.js"></script>

<style>
body {margin:0;}

.top-head{
    list-style-type: none;
    margin: 0;
    padding: 0;
    overflow: hidden;
    background-color: #333;
}

ul b {
    display: block;
    color: white;
    text-align: center;
    padding: 14px 16px;
    text-decoration: none;
}



li {
    float: left;
    border-right:1px solid #bbb;
}

li a {
    display: block;
    color: white;
    text-align: center;
    padding: 14px 16px;
    text-decoration: none;
}

li a:hover:not(.active) {
    background-color: #111;
}

.active {
    background-color: #4CAF50;
}


.mid-box {
    border-radius: 5px;
    background-color: #f2f2f2;
    padding: 40px;

    width:50%;
    margin: auto;
    padding: 10px;

}

input[type=text], select {

}

input[type=submit] {

}

.submit{
    width: 25%;
    background-color: #4CAF50;
    color: white;
    padding: 14px 20px;
    border: none;
    border-radius: 4px;
    cursor: pointer;
    font-size: 16px;
    }

.middle-save-bt{
    margin: 8px 37% -8px;
    }

.word-text{
    width: 100%;
    height: 25%;
    padding: 12px 20px;
    box-sizing: border-box;
    border: 2px solid #ccc;
    border-radius: 4px;
    background-color: #f8f8f8;
    font-size: 16px;
    resize: none;
    }

.search {
        width: 30%;
    box-sizing: border-box;
    border: 2px solid #ccc;
    border-radius: 4px;
    font-size: 16px;
    background-color: white;
    background-image:  url('images/search.png');
    background-position: 10px 10px;
    background-repeat: no-repeat;
    padding: 12px 20px 12px 40px;
    }

input[type=submit]:hover {
    background-color: #45a049;
}


textarea {
    width: 100%;
    height: 25%;
    padding: 12px 20px;
    box-sizing: border-box;
    border: 2px solid #ccc;
    border-radius: 4px;
    background-color: #f8f8f8;
    font-size: 16px;
    resize: none;
}


.select {
    width: 100%;
    padding: 16px 20px;
    border: none;
    border-radius: 4px;
    background-color: ;
}

</style>

<script>
function set_property() {
    var text_content = document.getElementById("content")
    text_content.style.fontSize = document.getElementById("font_size").value+"px";
    text_content.style.color = document.getElementById("choose_color").value;
}


var app = angular.module('fontsizeApp', []);
app.controller('fontsizeCtrl', function($scope) {
    $scope.fontSize = document.getElementById("font_size").value;
});


function uploadOnChange() {
    var filename = this.value;
    var lastIndex = filename.lastIndexOf("\\");
    if (lastIndex >= 0) {
        filename = filename.substring(lastIndex + 1);
    }
        document.getElementById('filename').value = ".. image:: /static/rstapp/images/"+filename;
}

</script>

</head>
<body>

<ul class="top-head">
  <li><a class="active" href="{% url 'rstapp:home' %}">Home</a></li>
  <li><a href="{% url 'rstapp:presentation_list' %}">Presentation List</a></li>
    <li><a href="">Download / Upload</a></li>
  <ul style="float:right;list-style-type:none;">
    <li><a href="#about">About</a></li>
    <li><a href="admin">Admin</a></li>
  </ul>
</ul>
<br>
<br>
<br>
<center><h1>Create Presentation</h1></center>
<div ng-app="fontsizeApp" ng-controller="fontsizeCtrl">

<div class="mid-box">

  <form action="{% url 'rstapp:create_rst' %}" method="post" enctype="multipart/form-data">
      {% csrf_token %}

      <center><h2><label for="presentation_name" ><b>Presentation Name</b></label></h2></center>
      <input placeholder="Name.." class="word-text" type="text" id="presentation_name" name="presentation_name" required><br><br>

      Color: <input type="color" id="choose_color" onchange="set_property()" name="favcolor" value="#000000">
      Font Size: <input ng-model="fontSize" type="range" id="font_size" value="16" name="points" min="5" max="40" onchange="set_property()">{%verbatim%} {{fontSize}} {%endverbatim%}
      <br>Upload Picture:

      <input id="upload" name="upload" type="file" >
      <script> document.getElementById('upload').onchange = uploadOnChange;</script>
      Picture Url : <input id="filename" type="text" />

      <br><br>

       <textarea placeholder="Write something here..
======================
example
=======
* Your topic.
* Your content.
* etc... " id="content" name="content" cols="100" rows="30" required></textarea>

      <br><br>
      <label for="style_presentation"><b>Style of Presentation</b></label><br><br>
       <select class="select" id="style_presentation" name="style_presentation">
        <option value="">Clean</option>
        <option value="--deck-js">Deck</option>
        <option value="--jquery --reveal-js">Reveal</option>
        <option value="--jquery --bootstrap-css">Bootstrap</option>
       </select><br><br>

    <center><input type="submit" class="submit" value="Create"></center>
  </form>
</div></div>

{% if error_message %}<p style="text-align: center; font-size:150%;"><strong>{{ error_message }}</strong></p>{% endif %}


</body>
</html>

rstapp/templates/rstapp/presentation_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Presentation List</title>

{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'rstapp/style.css' %}" />

<script src="http://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.min.js"></script>


</head>
<body>

<ul class="top-head">
  <li><a href="{% url 'rstapp:home' %}">Home</a></li>
  <li><a class="active" href="">Presentation List</a></li>
    <li><a href="">Download / Upload</a></li>
  <ul style="float:right;list-style-type:none;">
    <li><a href="#about">About</a></li>
    <li><a href="admin">Admin</a></li>
  </ul>
</ul>
<center>

<div ng-app="myApp" ng-controller="namesCtrl">

<h1>Presentation List</h1>

<p><input placeholder="Search" class="search" type="text" id="search" name="search" ng-model="test"></p>


  <p ng-repeat="x in names | filter:test">
   {%verbatim%} {{ x }} {%endverbatim%}
  </p>


</div>
</center>
<script>
angular.module('myApp', []).controller('namesCtrl', function($scope) {
    $scope.names = {{ latest_presentation_list|safe }}
});
</script>


</body>
</html>